import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

import { Input } from '@chakra-ui/react'
import { Button, ButtonGroup } from '@chakra-ui/react'
import { Select } from '@chakra-ui/react'

import bodyParser from "body-parser";
import util from "util";
import axios from "axios";

const getBody = util.promisify(bodyParser.urlencoded());

const Home: NextPage = () => {
  const router = useRouter();

  const [questionTitle, setQuestionTitle] = useState();

  const submitQuestion = () => {

      //post to axios then redirect somewhere

  } 

  return (
      <>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <form action="/ask_question" method="post">
              title<input name="title"/>
              <br/>
              <Input placeholder='Basic usage' />
              <br/>
              caterogy-car accident/estate law/startup law/real estate law
              <br/>
              <Select name="category">
                <option value="">Car Accident</option>
                <option value="">Estate Law</option>
                <option value="">Startup Law</option>
              </Select>
              <br/>
              state legal question relates to
              <br/>
              <Select name="state">
                <option value="">CA</option>
                <option value="">TX</option>
                <option value="">NY</option>
              </Select>
              <br/>
              question-(dont include names)
              <br/>
              <textarea name="question" rows={25} cols={100}></textarea>
              <br/>
              add images-blur license plates and people
              <br/>
              <br/>
              <Button type="submit">Submit question</Button>
            </form>
          </main>

          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a>
          </footer>
        </div>
      </>
  )
}

export const getServerSideProps = async ({ req, res }: any) => {

    //const router = useRouter(); 

    await getBody(req, res);
    console.log("title" + JSON.stringify(req.body["title"]));

    //router.push("/homepage");

    //return {
    //  redirect: {
    //    permanent: false,
    //    destination: `/homepage`
    //  },
    //};

    //check db for email and password
    //if error then redirect bac
    //else go to homepage
    //router.push("/homepage");

    /*try {
      const response = await axios.get(
        `https://api.example.com/getHomeSection?title=Section 1`
      );
      
      return {
        props: {
          show: response.data,
        },
      };
    } catch (error) {
      return {
        props: {
          error: error.error,
        },
      };
    }*/

    return {props: {}};

};


export default Home
