import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const ManageLegalCase: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        date of incident
        <br/>
        i am suing another driver for hiting my car and lying about it
        <br/>
        tasks - develop timeline - witnesses - evidence
        <br/>
        <Link href="/manage_legal_case/manage_legal_case_notes">manage case notes</Link>
        <br/>
        Witness
        <br/>
        Questions
        <br/>
        <Link href="/manage_legal_case/manage_legal_case_timeline">Timeline</Link>
        <br/>
        Photoes
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default ManageLegalCase
